MvcGrabBag.Web/Controllers/CacheController.cs
using System;
using System.Web.Mvc;
using MvcGrabBag.Web.Caching;

namespace MvcGrabBag.Web.Controllers
{
    public class CacheController : Controller
    {
        private readonly ICache _cache;

        public CacheController() : this(new HttpCache())
        {
        }

        public CacheController(ICache cache)
        {
            _cache = cache;
        }


        public ActionResult Bad()
        {
            var firstVisit = HttpContext.Cache.Get("FirstVisit") as DateTime?;
            if (firstVisit == null)
            {
                firstVisit = DateTime.Now;
                HttpContext.Cache.Insert("FirstVisit", firstVisit, null, DateTime.Now.AddMinutes(1), TimeSpan.Zero);
            }

            return View("Index", firstVisit.Value);
        }

        public ActionResult Index()
        {
            var firstVisit = _cache.Get(CacheScope.User, "FirstVisit", TimeSpan.FromMinutes(1), () => DateTime.Now);
            return View(firstVisit);
        }

        public ActionResult FullyAbstracted()
        {
            var firstVisit = AppCache.UsersFirstVisit;
            return View("Index", firstVisit);
        }

    }

    /// <summary>
    /// This class demonstrates fully abstracting the details of your caching strategy and could serve as the single entry point for cached data
    /// </summary>
    public static class AppCache
    {
        public static ICache InternalCache = new HttpCache();

        public static DateTime UsersFirstVisit = InternalCache.Get(CacheScope.User, "FirstVisit", TimeSpan.FromMinutes(1), () => DateTime.Now);
    }
}

MvcGrabBag.Web/Controllers/SelectorController.cs
using System.Web.Mvc;
using MvcGrabBag.Web.Models;

namespace MvcGrabBag.Web.Controllers
{
    public class SelectorController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var model = new DisplayModeOptions();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(DisplayModeOptions input)
        {
            if (!ModelState.IsValid)
                return View(input);

            return RedirectToAction("Index");
        }
    }
}

MvcGrabBag.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width">
        <title>@ViewBag.Title - MvcGrabBag</title>
                @Html.Telerik().StyleSheetRegistrar().DefaultGroup(group => group.DefaultPath("~/Content/2011.3.1115")
                .Add("telerik.common.min.css")
                 .Add("telerik.windows7.min.css"))


        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

        <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.js")" type="text/javascript"></script>

        <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/requiredfileupload.js")" type="text/javascript"></script>

        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        
        @Html.Telerik().ScriptRegistrar().jQuery(false)
        
        <script type="text/javascript">
            (function ($) {
                

                $.validator.addMethod("selector", function (value, element, params) {

                    if (!this.optional(element)) {
                        var otherProp = $('#' + params);
                        return (otherProp.val() != value);
                    }
                    return false;
                });
                $.validator.unobtrusive.adapters.addSingleVal("selector", "minlength");
            } (jQuery));

        </script>
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("MvcGrabBag", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                      
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("HtmlFormHelper", "NewProduct", "HtmlFormHelper")</li>
                            <li>@Html.ActionLink("Selectors", "Index", "Selector")</li>
                            <li>@Html.ActionLink("Caching", "Index", "Cache")</li>
                            <li>@Html.ActionLink("UploadedFile", "Index", "UploadedFile")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - MvcGrabBag</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>